/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard.sessions'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardInsiderRouteImport } from './routes/dashboard.insider'
import { Route as DashboardGraphRouteImport } from './routes/dashboard.graph'
import { Route as AuthResultRouteImport } from './routes/auth.result'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsiderRoute = DashboardInsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGraphRoute = DashboardGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResultRoute = AuthResultRouteImport.update({
  id: '/auth/result',
  path: '/auth/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/auth/result': typeof AuthResultRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/auth/result': typeof AuthResultRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/auth/result': typeof AuthResultRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/transfer'
    | '/auth/result'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/onboarding'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/transfer'
    | '/auth/result'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/onboarding'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/recovery'
    | '/signup'
    | '/transfer'
    | '/auth/result'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/onboarding'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
  SignupRoute: typeof SignupRoute
  TransferRoute: typeof TransferRoute
  AuthResultRoute: typeof AuthResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insider': {
      id: '/dashboard/insider'
      path: '/insider'
      fullPath: '/dashboard/insider'
      preLoaderRoute: typeof DashboardInsiderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/graph': {
      id: '/dashboard/graph'
      path: '/graph'
      fullPath: '/dashboard/graph'
      preLoaderRoute: typeof DashboardGraphRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/result': {
      id: '/auth/result'
      path: '/auth/result'
      fullPath: '/auth/result'
      preLoaderRoute: typeof AuthResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardGraphRoute: typeof DashboardGraphRoute
  DashboardInsiderRoute: typeof DashboardInsiderRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGraphRoute: DashboardGraphRoute,
  DashboardInsiderRoute: DashboardInsiderRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
  SignupRoute: SignupRoute,
  TransferRoute: TransferRoute,
  AuthResultRoute: AuthResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
